// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaProject;
using SpaProject.Data;

#nullable disable

namespace SpaProject.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20220401165651_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("SpaProject.Models.CustomersTrack", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Department")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InorOut")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomerId");

                    b.ToTable("CustomersTrack");
                });

            modelBuilder.Entity("SpaProject.Models.Sauna", b =>
                {
                    b.Property<Guid>("SaunaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AllTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("SaunaId");

                    b.ToTable("Sauna");
                });
#pragma warning restore 612, 618
        }
    }
}
